# https://taskfile.dev

version: '3'
tasks:
  android:
    cmds:
      - cd mobile && cmd /c build-android.bat
    sh: false
    silent: false
  windows:
    cmds:
      - cd cmd/rush && go build -ldflags="-s -w" -o rush.exe
    silent: false
  wasm:
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - cd cmd/rush && go build -ldflags="-s -w" -o rush.wasm
    silent: false
